KZSE: KBLI airport fully completed.
ivao-xa/sectorfiles pull request #82
Opened 2021-06-07 10:39 UTC by AlexSkeleton12

Exception: Taxiway C a little broken.

Closes #81.

2021-06-07 13:57 UTC, wessupermare requested changes
Looks like parts of taxiway C are missing as well as some runway bleed and the inclusion of some closed taxiways. If you could fix C, remove the unused portions of the airport, and limit the box around the runway to line up with the FAA airport diagram, that would be great.

2021-06-07 19:07 UTC, aldobenitez approved these changes

2021-06-07 19:09 UTC, aldobenitez commented
Sorry accidently approved it.

2021-06-12 03:29 UTC, aldobenitez approved these changes

2021-06-12 03:30 UTC, aldobenitez commented
> Looks like parts of taxiway C are missing as well as some runway bleed and the inclusion of some closed taxiways. If you could fix C, remove the unused portions of the airport, and limit the box around the runway to line up with the FAA airport diagram, that would be great.

Unused taxiways removed, runways move to bottom of file. Verified visually in Aurora and can be pulled.

2021-06-12 03:31 UTC, aldobenitez approved these changes

2021-06-12 15:35 UTC, IVAO-NorthAmerica approved these changes

2021-06-12 20:53 UTC, wessupermare approved these changes

2021-06-12 20:53 UTC, merged